workflows:
  ios-build:
    name: iOS Build (no codesign)
    max_build_duration: 60
    instance_type: mac_mini_m2

    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
      tag_patterns:
        - pattern: '*'
          include: true

    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Convert .app to .ipa
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r bicone_unsigned.ipa Payload
    artifacts:
      - build/ios/iphoneos/bicone_unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
